// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLKW63XlXt92gI12JOrz2AyM3FeE6yTgU',
    appId: '1:596616923486:web:08e56e6b8c9ca4438de7cf',
    messagingSenderId: '596616923486',
    projectId: 'auth-example-a228c',
    authDomain: 'auth-example-a228c.firebaseapp.com',
    storageBucket: 'auth-example-a228c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_F3GP88pWCRcTpfwapm6Iq9WQW5SQ8sA',
    appId: '1:596616923486:android:ba6f49dea5ded2ce8de7cf',
    messagingSenderId: '596616923486',
    projectId: 'auth-example-a228c',
    storageBucket: 'auth-example-a228c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKQj2Py83RsUh7HawGLEX427WUcFfRJpo',
    appId: '1:596616923486:ios:3555a937df754ca28de7cf',
    messagingSenderId: '596616923486',
    projectId: 'auth-example-a228c',
    storageBucket: 'auth-example-a228c.appspot.com',
    iosClientId: '596616923486-s8c18tntemctinqhm6ato7p88eirqf8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKQj2Py83RsUh7HawGLEX427WUcFfRJpo',
    appId: '1:596616923486:ios:3555a937df754ca28de7cf',
    messagingSenderId: '596616923486',
    projectId: 'auth-example-a228c',
    storageBucket: 'auth-example-a228c.appspot.com',
    iosClientId: '596616923486-s8c18tntemctinqhm6ato7p88eirqf8c.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
